services:
  cbt-timelapse-frontend:
    container_name: cbt-timelapse-frontend
    build:
      context: ./cbt_timelapses_frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=12345
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
